########listarFoto########
GET http://localhost:3000/foto HTTP/1.1


########ATUALIZAR, NÃO SEI MANDAR FOTO POR AQUI, PELO POSTMAN VAI########

POST http://localhost:3000/foto HTTP/1.1
content-type: application/json

{
    "nome": "nome",
    "evento": {"_id": "62703144e306b169d8ac5f39"},
    "foto": "urlfoto",
    "banner": false

}

########listarFotoID########
GET http://localhost:3000/foto/62703b3a269bd4d15640af28 HTTP/1.1


########excluirFotoID########
DELETE  http://localhost:3000/foto/62703b3a269bd4d15640af28 HTTP/1.1