GET http://localhost:3000/foto HTTP/1.1


########

POST http://localhost:3000/foto HTTP/1.1
content-type: application/json

{
    "nome": "nome",
    "evento": "evento",
    "foto": "urlfoto",
    "banner": false

}