########listarUsuario########
GET http://localhost:3000/usuario HTTP/1.1

####Autenticação########
POST http://localhost:3000/auth HTTP/1.1
content-type: application/json
Authorization:

{
    "email":"lucas@lucas.com",
    "senha":"123456789110"
}

########novoUsuario########

POST http://localhost:3000/usuario HTTP/1.1
content-type: application/json

{
    "nome": "aaa",
    "sobrenome": "sobrenome",
    "email":"lucaas@lucas.com",
    "senha":"12345678910"

}

########listarUsuarioID########
GET http://localhost:3000/usuario/627abe965c71547556610470 HTTP/1.1


########atualizarUsuarioID########
PUT http://localhost:3000/usuario/627abe965c71547556610470 HTTP/1.1
content-type: application/json

{
    "nome": "aab",
    "sobrenome": "sobrenome",
    "email": "a@a.com",
    "senha": "12345678910" 

}
########excluirUsuarioID########
DELETE http://localhost:3000/usuario/627abe965c71547556610470 HTTP/1.1
